version: "3.8"

services:
  service-b:
    container_name: pms-demo-service-b
    image: ghcr.io/xywhnh/pms-demo-ai-service-b:latest
    restart: unless-stopped
    ports:
      - "8082:8082"
    volumes:
      - ./logs/service-b:/app/logs
    security_opt:
      - seccomp=unconfined
    networks:
      - pms-demo-net

  service-a:
    container_name: pms-demo-service-a
    image: ghcr.io/xywhnh/pms-demo-ai-service-a:latest
    restart: unless-stopped
    depends_on:
      - service-b
    environment:
      SERVICE_B_BASE_URL: http://service-b:8082
    ports:
      - "8081:8081"
    volumes:
      - ./logs/service-a:/app/logs
    security_opt:
      - seccomp=unconfined
    networks:
      - pms-demo-net

networks:
  pms-demo-net:
    driver: bridge
