server:
  port: 8081

spring:
  application:
    name: demo-service-a

service-b:
  base-url: ${SERVICE_B_BASE_URL:http://localhost:8082}

service-c:
  base-url: ${SERVICE_C_BASE_URL:http://localhost:8083}

logging:
  level:
    com.glodon.pms.demo: DEBUG
